import type { AccessibilitySettings, AccessibilityFeature, AccessibilityProfile } from '@/types/accessibility';

export const defaultAccessibilitySettings: AccessibilitySettings = {
  fontSize: 'default',
  lineHeight: 1.5,
  letterSpacing: 0,
  fontFamily: 'default',
  contrast: 'default',
  colorScheme: 'default',
  grayscale: false,
  highlightLinks: false,
  underlineLinks: false,
  largePointer: false,
  readingGuide: false,
  textToSpeech: false,
  hideImages: false,
  pauseAnimations: false,
  enableKeyboardNav: true,
};

export const accessibilityProfiles: AccessibilityProfile[] = [
  {
    id: 'default',
    namePT: 'Padrão',
    nameEN: 'Default',
    descriptionPT: 'Configurações padrão do sistema',
    descriptionEN: 'Default system settings',
    iconPT: '⚙️',
    iconEN: '⚙️',
    settings: defaultAccessibilitySettings,
  },
  {
    id: 'dyslexia',
    namePT: 'Dislexia',
    nameEN: 'Dyslexia',
    descriptionPT: 'Fonte especial, maior espaçamento e guia de leitura',
    descriptionEN: 'Special font, increased spacing and reading guide',
    iconPT: '📖',
    iconEN: '📖',
    settings: {
      fontSize: 'large',
      lineHeight: 1.8,
      letterSpacing: 2,
      fontFamily: 'dyslexia-friendly',
      highlightLinks: true,
      underlineLinks: true,
      readingGuide: true,
      pauseAnimations: true,
    },
  },
  {
    id: 'low-vision',
    namePT: 'Baixa Visão',
    nameEN: 'Low Vision',
    descriptionPT: 'Texto grande, alto contraste e cursor aumentado',
    descriptionEN: 'Large text, high contrast and large cursor',
    iconPT: '👁️',
    iconEN: '👁️',
    settings: {
      fontSize: 'extra-large',
      lineHeight: 2.0,
      letterSpacing: 1.5,
      contrast: 'high',
      colorScheme: 'dark-bg',
      highlightLinks: true,
      underlineLinks: true,
      largePointer: true,
    },
  },
  {
    id: 'motor-impairment',
    namePT: 'Dificuldade Motora',
    nameEN: 'Motor Impairment',
    descriptionPT: 'Botões grandes, cursor aumentado e sem animações',
    descriptionEN: 'Large buttons, large cursor and no animations',
    iconPT: '🖱️',
    iconEN: '🖱️',
    settings: {
      fontSize: 'large',
      lineHeight: 1.8,
      largePointer: true,
      pauseAnimations: true,
      highlightLinks: true,
      underlineLinks: true,
    },
  },
  {
    id: 'photosensitive',
    namePT: 'Fotossensibilidade',
    nameEN: 'Photosensitive',
    descriptionPT: 'Sem animações, cores suaves e filtro cinza',
    descriptionEN: 'No animations, soft colors and grayscale filter',
    iconPT: '🌙',
    iconEN: '🌙',
    settings: {
      pauseAnimations: true,
      grayscale: true,
      hideImages: false,
      contrast: 'default',
      colorScheme: 'light-bg',
    },
  },
];

export const accessibilityFeatures: AccessibilityFeature[] = [
  {
    id: 'fontSize',
    labelPT: 'Tamanho do Texto',
    labelEN: 'Font Size',
    type: 'select',
    defaultValue: 'default',
    options: [
      { value: 'default', labelPT: 'Padrão (16px)', labelEN: 'Default (16px)' },
      { value: 'medium', labelPT: 'Médio (18px)', labelEN: 'Medium (18px)' },
      { value: 'large', labelPT: 'Grande (20px)', labelEN: 'Large (20px)' },
      { value: 'extra-large', labelPT: 'Extra Grande (24px)', labelEN: 'Extra Large (24px)' },
    ],
  },
  {
    id: 'lineHeight',
    labelPT: 'Altura da Linha',
    labelEN: 'Line Height',
    type: 'increment',
    defaultValue: 1.5,
    min: 1.0,
    max: 2.0,
    step: 0.1,
  },
  {
    id: 'letterSpacing',
    labelPT: 'Espaçamento de Letras',
    labelEN: 'Letter Spacing',
    type: 'increment',
    defaultValue: 0,
    min: 0,
    max: 5,
    step: 0.5,
  },
  {
    id: 'fontFamily',
    labelPT: 'Tipo de Fonte',
    labelEN: 'Font Family',
    type: 'select',
    defaultValue: 'default',
    options: [
      { value: 'default', labelPT: 'Padrão', labelEN: 'Default' },
      { value: 'readable', labelPT: 'Legível', labelEN: 'Readable' },
      { value: 'dyslexia-friendly', labelPT: 'Dislexia', labelEN: 'Dyslexia-Friendly' },
    ],
  },
  {
    id: 'contrast',
    labelPT: 'Contraste',
    labelEN: 'Contrast',
    type: 'select',
    defaultValue: 'default',
    options: [
      { value: 'default', labelPT: 'Padrão', labelEN: 'Default' },
      { value: 'high', labelPT: 'Alto', labelEN: 'High' },
      { value: 'inverted', labelPT: 'Invertido', labelEN: 'Inverted' },
    ],
  },
  {
    id: 'colorScheme',
    labelPT: 'Esquema de Cores',
    labelEN: 'Color Scheme',
    type: 'select',
    defaultValue: 'default',
    options: [
      { value: 'default', labelPT: 'Padrão', labelEN: 'Default' },
      { value: 'grayscale', labelPT: 'Cinza', labelEN: 'Grayscale' },
      { value: 'light-bg', labelPT: 'Fundo Claro', labelEN: 'Light Background' },
      { value: 'dark-bg', labelPT: 'Fundo Escuro', labelEN: 'Dark Background' },
    ],
  },
  {
    id: 'highlightLinks',
    labelPT: 'Destacar Links',
    labelEN: 'Highlight Links',
    type: 'toggle',
    defaultValue: false,
  },
  {
    id: 'underlineLinks',
    labelPT: 'Sublinhar Links',
    labelEN: 'Underline Links',
    type: 'toggle',
    defaultValue: false,
  },
  {
    id: 'readingGuide',
    labelPT: 'Guia de Leitura',
    labelEN: 'Reading Guide',
    type: 'toggle',
    defaultValue: false,
  },
  {
    id: 'pauseAnimations',
    labelPT: 'Pausar Animações',
    labelEN: 'Pause Animations',
    type: 'toggle',
    defaultValue: false,
  },
  {
    id: 'grayscale',
    labelPT: 'Filtro Cinza',
    labelEN: 'Grayscale Filter',
    type: 'toggle',
    defaultValue: false,
  },
  {
    id: 'hideImages',
    labelPT: 'Ocultar Imagens',
    labelEN: 'Hide Images',
    type: 'toggle',
    defaultValue: false,
  },
];

export const STORAGE_KEY = 'help-nexus-accessibility-settings';
