// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrwkxpyxmtuxushnfbts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpyd2t4cHl4bXR1eHVzaG5mYnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDk5ODYsImV4cCI6MjA3MzYyNTk4Nn0.rV19OZRRyMSnnYP6wCwzgeheX9v8YotA2fdy2Nx9Psw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});